language: go
go:
 - 1.9.2
before_cache:
  - ccache -s
cache:
  directories:
    - $HOME/.ccache
install:
 - mkdir -p $HOME/.ccache
 - export PATH=/usr/lib/ccache:$PATH
 - sudo apt-get install protobuf-compiler
 - go get -u github.com/jteeuwen/go-bindata/...
 - go get -d github.com/ry/v8worker2
 - (cd $GOPATH/src/github.com/ry/v8worker2 && ./tools/build.py)
script:
 - make lint
 - make test
