language: go
go:
 - 1.9.2
cache:
  directories:
   - $HOME/.ccache
install:
 - sudo apt-get install protobuf-compiler
 - go get -u github.com/jteeuwen/go-bindata/...
 - go get -d github.com/ry/v8worker2
 - (cd $GOPATH/src/github.com/ry/v8worker2 && ./tools/build.py)
script:
 - make lint
 - make test
