language: c++
cache: ccache
cache:
  directories:
   - .cache/
   - node_modules/
env:
  global:
    - PROTOBUF_ROOT=$HOME/protobuf
before_install: |
  # protobuf
  export PATH=$PROTOBUF_ROOT/bin:$PATH
  if ! [ -x $PROTOBUF_ROOT/bin/protoc ]; then
    rm -rf $PROTOBUF_ROOT
    mkdir -p $PROTOBUF_ROOT
    pushd $PROTOBUF_ROOT
    wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
    unzip protoc-3.1.0-linux-x86_64.zip
    popd
  fi
install:
 - env
 - go get -d github.com/ry/v8worker2
 - ( cd $GOPATH/src/github.com/ry/v8worker2 && ./build.py --use_ccache )
 - go get -u github.com/golang/protobuf/proto
 - go get -u github.com/spf13/afero
 - go get -u github.com/golang/protobuf/protoc-gen-go
 - go get -u github.com/jteeuwen/go-bindata/...
 - yarn
script:
 - make lint
 - make test
