language: c++
branches:
  only:
  - master
cache:
  ccache: true
  directories:
   - $CARGO_PATH
   - $RUSTUP_PATH
   - third_party/v8/build/linux/debian_sid_amd64-sysroot/
   - third_party/v8/third_party/llvm-build/
env:
  global:
    - CARGO_PATH=$HOME/.cargo/
    - RUSTUP_PATH=$HOME/.rustup/
    # is_debug, use_allocator, and ccache are used to speed travis.
    # use_custom_libcxx=false and use_sysroot=false seem to be required to build on
    # Ubuntu 14.04
    # Help: How do you wrap long lines here?
    - DENO_BUILD_ARGS="is_debug=false use_allocator=\"none\" use_custom_libcxx=false use_sysroot=false"
    - DENO_BUILD_PATH=$HOME/out/Default
    - DENO_BUILD_MODE=debug
before_install: |
  # Install Rust.
  # TODO(ry) Include rustc in third_party https://github.com/denoland/deno/issues/386
  export PATH=$CARGO_PATH/bin:$PATH
  rustc --version
  if [ $? != 0 ]; then
    curl -sSf https://sh.rustup.rs | sh -s -- -y
  fi
install:
 # ccache needs the custom LLVM to be in PATH and other variables.
 - export PATH=`pwd`/third_party/llvm-build/Release+Asserts/bin:$PATH
 - export CCACHE_CPP2=yes
 - export CCACHE_SLOPPINESS=time_macros
 - ccache -s
 - ./tools/setup.py
 # Travis hangs without -j2 argument to ninja.
 - ./tools/build.py -j2
script:
 - ./tools/lint.py
 - ./tools/test.py $DENO_BUILD_PATH
