language: go
go:
 - 1.9.2
before_cache:
  - ccache -s
cache:
  directories:
    - $HOME/.ccache
    - $PROTOBUF_ROOT
env:
  global:
    - USE_CCACHE=1
    - PROTOBUF_ROOT=$HOME/protobuf
before_install: |
  export PATH=$PROTOBUF_ROOT/bin:$PATH
  if ! [ -x $PROTOBUF_ROOT/bin/protoc ]; then
    rm -rf $PROTOBUF_ROOT
    mkdir -p $PROTOBUF_ROOT
    pushd $PROTOBUF_ROOT
    wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
    unzip protoc-3.1.0-linux-x86_64.zip
    popd
  fi
install:
 - mkdir -p $HOME/.ccache
 - export PATH=/usr/lib/ccache:$PATH
 - go get -u github.com/jteeuwen/go-bindata/...
 - go get -d github.com/ry/v8worker2
 - (cd $GOPATH/src/github.com/ry/v8worker2 && ./tools/build.py)
 - yarn
script:
 - yarn lint-version
 - make lint
 - make test
