language: c++
cache:
  ccache: true
  directories:
   - .cache/
   - node_modules/
   - $V8WORKER2_OUT_PATH
before_script:
  - mkdir -p $DENO_PATH
  - cd $DENO_PATH
env:
  global:
    - V8WORKER2_OUT_PATH=$HOME/v8worker2_out
    - PROTOBUF_ROOT=$HOME/protobuf
    - DENO_PATH=/home/travis/gopath/src/github.com/ry/deno
before_install: |
  # protobuf
  export PATH=$PROTOBUF_ROOT/bin:$PATH
  if ! [ -x $PROTOBUF_ROOT/bin/protoc ]; then
    rm -rf $PROTOBUF_ROOT
    mkdir -p $PROTOBUF_ROOT
    pushd $PROTOBUF_ROOT
    wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
    unzip protoc-3.1.0-linux-x86_64.zip
    popd
  fi
install:
 - env
 - go get -d github.com/ry/v8worker2
 - $GOPATH/src/github.com/ry/v8worker2/build.py --use_ccache --out_path $V8WORKER2_OUT_PATH
 - go get -u github.com/golang/protobuf/proto
 - go get -u github.com/spf13/afero
 - go get -u github.com/golang/protobuf/protoc-gen-go
 - go get -u github.com/jteeuwen/go-bindata/...
 - yarn
script:
 - make lint
 - make test
