language: c++
branches:
  only:
  - master
cache:
  ccache: true
  directories:
   - $DENO_BUILD_PATH
env:
  global:
    # is_debug, use_allocator, and ccache are used to speed travis.
    # use_custom_libcxx=false and use_sysroot=false seem to be required to build on
    # Ubuntu 14.04
    # Help: How do you wrap long lines here?
    - DENO_BUILD_ARGS="is_debug=false use_allocator=\"none\" use_custom_libcxx=false use_sysroot=false"
    - DENO_BUILD_PATH=$HOME/out/Default
    - DENO_BUILD_MODE=debug
install:
 # Sync dependencies.
 # TODO(ry) These sync steps are very terrible and only here temporarily.
 # rustc should be added to deno_third_party. Ultimately Deno *should not*
 # depend on yarn, gclient, rustup, cargo, nor any internet connection.
 - curl -sSf https://sh.rustup.rs | sh -s -- -y
 - export PATH=$HOME/.cargo/bin:$PATH
 - rustc --version
 # ccache needs the custom LLVM to be in PATH and other variables.
 - export PATH=`pwd`/third_party/llvm-build/Release+Asserts/bin:$PATH
 - export CCACHE_CPP2=yes
 - export CCACHE_SLOPPINESS=time_macros
 - ccache -s
 - ./tools/setup.py
 - ./tools/build.py
script:
 - ./tools/lint.py
 - ./tools/test.py $DENO_BUILD_PATH
